export const LOADING = "LOADING"
export const GET_FLIGHTS_SUCCESS = "GET_ALL_SUCCESS"
export const GET_CITY_SUCCESS = "GET_ITEM_SUCCESS"
export const GET_FLIGHTS_LOCAL_SUCCESS = "GET_FLIGHTS_LOCAL_SUCCESS"
